department: 디자인 부문
head: 디자인 부문
jobs:
  - title: UI 디자이너 (경력)
    description:
      - 리디북스 Android/iOS/Mac/Windows/PAPER 앱 디자인
      - 리디북스 서점 웹사이트 디자인
      - 신규 서비스 앱/웹사이트 디자인
      - <a href="/career/senior-ui-designer">리디북스 UI 디자이너 소개</a>
    required:
      - 디자인 경력 3년 이상
      - 웹 또는 앱 서비스 디자인에 깊이 참여한 경험
      - 높은 수준의 커뮤니케이션 능력
    preferred:
      - 아이콘/일러스트레이션 능력
      - HTML/CSS/Javascript 능력
    link: https://ridi.typeform.com/to/G1L0xH

  - title: 모션그래픽 디자이너
    description:
      - 콘텐츠 소개 모션그래픽 제작
      - Kinetic Typography & Animating
    required:
      - 감각적인 모션그래픽 능력
      - 훌륭한 커뮤니케이션 능력
      - 웹 콘텐츠에 대한 이해
    preferred:
      - 미술/디자인 전공자 우대
      - 드로잉/일러스트레이션 능력 우대
      - 3D작업 가능자 우대
    link: https://ridi.typeform.com/to/G1L0xH